[package]
name = "bitbox-api"
authors = ["Marko Bencun <benma@bitbox.swiss>"]
version = "0.13.1"
homepage = "https://bitbox.swiss/"
repository = "https://github.com/BitBoxSwiss/bitbox-api-rs/"
readme = "README.md"
edition = "2021"
license = "Apache-2.0"
description = "A library to interact with BitBox hardware wallets"
keywords = ["bitbox", "api", "bitcoin"]
categories = ["api-bindings", "cryptography"]

[dependencies]
async-trait = "0.1.68"
base32 = "0.5"
bitcoin = "0.32"
byteorder = "1.3.2"
getrandom = { version = "0.2" }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
hex = { version = "0.4" }
noise-protocol = "0.2"
noise-rust-crypto = "0.6"
num-bigint = "0.4"
# If you change this, also change the version of prost-build in scripts/build-protos.rs
# and run `make build-protos`.
prost = "0.14"
semver = "1.0.17"
serde_json = { version = "1.0" }
thiserror = "2.0"
zeroize = "1"

chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
hidapi = { version = "2.3", optional = true }
rlp = { version = "0.6", optional = true }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", optional = true, features = ["time"] }

[dev-dependencies]
# For the base64 PSBT input/output in examples/btc_sign_psbt.rs.
bitcoin = { version = "0.32", features = ["base64"] }
futures-channel = "0.3"
tokio = { version = "1", features = ["time", "macros", "rt", "fs"] }
reqwest = "0.12"
url = "2.5"
tiny-keccak = { version = "2.0", features = ["keccak"] }
rlp = "0.6"
# Enable this to be able to get coverage using `cargo tarpaulin --features=simulator,tokio --out=Html` without compilation error.
# See https://github.com/rust-bitcoin/rust-bitcoinconsensus/pull/94
# bitcoinconsensus = { git = "https://github.com/rust-bitcoin/rust-bitcoinconsensus.git", rev = "788ce4d210f7fe6fae4414f5be80968216ba0fd8", default-features = false }
bitcoinconsensus = { version = "0.106.0", default-features = false }
miniscript = "13.0.0"

[[example]]
name = "singlethreaded"
required-features = ["usb", "tokio/rt", "tokio/macros"]

[[example]]
name = "multithreaded"
required-features = ["usb", "tokio/rt", "tokio/macros", "tokio/rt-multi-thread", "multithreaded"]

[[example]]
name = "btc_signtx"
required-features = ["usb", "tokio/rt", "tokio/macros"]

[[example]]
name = "btc_sign_psbt"
required-features = ["usb", "tokio/rt", "tokio/macros"]

[[example]]
name = "btc_sign_op_return"
required-features = ["usb", "tokio/rt", "tokio/macros"]

[[example]]
name = "btc_sign_msg"
required-features = ["usb", "tokio/rt", "tokio/macros"]

[[example]]
name = "btc_miniscript"
required-features = ["usb", "tokio/rt", "tokio/macros"]

[[example]]
name = "eth"
required-features = ["usb", "tokio/rt", "tokio/macros", "rlp"]

[[example]]
name = "cardano"
required-features = ["usb", "tokio/rt", "tokio/macros"]

[[example]]
name = "simulator"
required-features = ["simulator", "tokio/rt", "tokio/macros", "tokio/rt-multi-thread", "multithreaded"]

[features]
# Implement Sync+Send for PairedBitBox and PairingBitBox.
# This may or may not cause trouble on macOS, see: https://github.com/libusb/hidapi/issues/503
multithreaded = []
usb = ["dep:hidapi"]
simulator = []
