// SPDX-License-Identifier: Apache-2.0

#![cfg(feature = "simulator")]
// Simulators only run on linux/amd64.
#![cfg(all(target_os = "linux", target_arch = "x86_64"))]

#[cfg(not(feature = "tokio"))]
compile_error!("Enable the tokio feature to run simulator tests");

mod util;

use std::collections::{BTreeMap, BTreeSet};
use std::time::Duration;

use bitbox_api::{pb, Keypath};
use bitcoin::bip32::{Fingerprint, Xpub};
use bitcoin::psbt::Psbt;
use bitcoin::secp256k1;
use bitcoin::sighash::{EcdsaSighashType, TapSighashType};
use miniscript::psbt::PsbtExt;
use semver::Version;
use serde::{de::IgnoredAny, Deserialize};
use util::{
    test_initialized_simulators_with_stdout, SimulatorScreen, SimulatorStdout,
    SimulatorStdoutCheckpoint, SimulatorStdoutSnapshot,
};

// Generated by bitbox02-firmware/src/rust/bitbox-test-vectors; do not edit the copy by hand.
const VECTOR_JSON: &str = include_str!("data/btc-transaction-test-vectors.json");
const STDOUT_STABLE_FOR: Duration = Duration::from_millis(50);
const STDOUT_TIMEOUT: Duration = Duration::from_secs(5);

// Checks that the psbt is fully signed and valid (all scripts execute correctly).
//
// Alternatively, we could use `miniscript::psbt::interpreter_check(&psbt, &secp).unwrap();` to
// verify the tx (this can only verify spends of UTXOs created by a descriptor, but the BitBox does
// not support anything else). We stick to libbitcoinconsensus for now for verification (not
// miniscript based) while it is still around. libbitcoinconsensus is dead
// (https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-27.0.md?plain=1#L40-L53)
// and will be replaced by libbitcoinkernel some day.
fn verify_transaction(psbt: Psbt) {
    let utxos: Vec<bitcoin::TxOut> = psbt
        .iter_funding_utxos()
        .map(|utxo| utxo.unwrap())
        .cloned()
        .collect();

    let tx = psbt.extract_tx_unchecked_fee_rate();
    let serialized_tx = bitcoin::consensus::encode::serialize(&tx);

    let flags = bitcoinconsensus::VERIFY_ALL_PRE_TAPROOT | bitcoinconsensus::VERIFY_TAPROOT;

    let utxos_converted: Vec<bitcoinconsensus::Utxo> = utxos
        .iter()
        .map(|output| bitcoinconsensus::Utxo {
            script_pubkey: output.script_pubkey.as_bytes().as_ptr(),
            script_pubkey_len: output.script_pubkey.as_bytes().len() as u32,
            value: output.value.to_sat() as i64,
        })
        .collect();

    for (idx, output) in utxos.iter().enumerate() {
        bitcoinconsensus::verify_with_flags(
            output.script_pubkey.as_bytes(),
            output.value.to_sat(),
            serialized_tx.as_slice(),
            Some(&utxos_converted),
            idx,
            flags,
        )
        .unwrap();
    }
}

#[derive(Deserialize)]
struct TestVectorFile {
    vectors: Vec<TestVector>,
}

#[derive(Deserialize)]
struct TestVector {
    id: String,
    description: String,
    coin: Coin,
    psbt: PsbtFixture,
    expectations: Vec<VersionExpectation>,
    #[serde(default)]
    registrations: Vec<Registration>,
    #[serde(default)]
    expected_signatures: BTreeSet<SignatureSlot>,
}

impl TestVector {
    fn context(&self) -> String {
        format!("{} ({})", self.id, self.description)
    }
}

#[derive(Deserialize)]
struct PsbtFixture {
    transaction: String,
    #[serde(default)]
    options: PsbtSignOptions,
}

#[derive(Clone, Copy, Deserialize)]
#[serde(rename_all = "snake_case")]
enum Coin {
    Btc,
    Tbtc,
    Ltc,
}

#[derive(Deserialize)]
struct VersionExpectation {
    min_version: Option<String>,
    max_version_exclusive: Option<String>,
    outcome: Outcome,
    unsupported_version: Option<String>,
    screens: Vec<ExpectedScreen>,
}

#[derive(Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
enum ExpectedScreen {
    Confirm {
        title: String,
        body: String,
    },
    TransactionAddress {
        amount: String,
        address: String,
    },
    TransactionFee {
        amount: String,
        fee: String,
    },
    Status {
        title: String,
        body: String,
    },
    Swap {
        title: String,
        from: String,
        to: String,
    },
}

impl ExpectedScreen {
    // `longtouch` is intentionally omitted: released simulators do not report it.
    fn observable(&self) -> SimulatorScreen {
        match self {
            Self::Confirm { title, body } => SimulatorScreen::Confirm {
                title: title.clone(),
                body: body.clone(),
            },
            Self::TransactionAddress { amount, address } => SimulatorScreen::TransactionAddress {
                amount: amount.clone(),
                address: address.clone(),
            },
            Self::TransactionFee { amount, fee } => SimulatorScreen::TransactionFee {
                amount: amount.clone(),
                fee: fee.clone(),
            },
            Self::Status { title, body } => SimulatorScreen::Status {
                title: title.clone(),
                body: body.clone(),
            },
            Self::Swap { title, from, to } => SimulatorScreen::Swap {
                title: title.clone(),
                from: from.clone(),
                to: to.clone(),
            },
        }
    }
}

#[derive(Clone, Copy, Deserialize)]
#[serde(rename_all = "snake_case")]
enum Outcome {
    Success,
    Unsupported,
    InvalidInput,
}

#[derive(Default, Deserialize)]
struct PsbtSignOptions {
    force_script_config: Option<ScriptConfigWithKeypath>,
    #[serde(default)]
    outputs: BTreeMap<usize, IgnoredAny>,
    #[serde(default)]
    payment_requests: Vec<IgnoredAny>,
    #[serde(default)]
    format_unit: FormatUnit,
}

#[derive(Clone, Copy, Default, Deserialize)]
#[serde(rename_all = "snake_case")]
enum FormatUnit {
    #[default]
    Default,
    Sat,
}

#[derive(Deserialize)]
struct ScriptConfigWithKeypath {
    script_config: ScriptConfig,
    keypath: String,
}

#[derive(Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
enum ScriptConfig {
    Simple {
        script_type: SimpleType,
    },
    Multisig {
        threshold: u32,
        xpubs: Vec<String>,
        our_xpub_index: u32,
        script_type: MultisigScriptType,
    },
    Policy {
        policy: String,
        keys: Vec<KeyOriginInfo>,
    },
}

#[derive(Deserialize)]
#[serde(rename_all = "snake_case")]
enum SimpleType {
    P2wpkh,
    P2wpkhP2sh,
    P2tr,
}

#[derive(Deserialize)]
#[serde(rename_all = "snake_case")]
enum MultisigScriptType {
    P2wsh,
    P2wshP2sh,
}

#[derive(Deserialize)]
struct KeyOriginInfo {
    root_fingerprint: Option<String>,
    keypath: Option<String>,
    xpub: String,
}

#[derive(Deserialize)]
struct Registration {
    script_config: ScriptConfig,
    keypath: Option<String>,
    name: String,
}

#[derive(Clone, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd)]
struct SignatureSlot {
    input_index: usize,
    kind: SignatureKind,
    pubkey: Option<String>,
    leaf_hash: Option<String>,
    sighash: Sighash,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd)]
#[serde(rename_all = "snake_case")]
enum SignatureKind {
    Ecdsa,
    TaprootKey,
    TaprootScript,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd)]
#[serde(rename_all = "snake_case")]
enum Sighash {
    All,
    Default,
}

fn expectation_for<'a>(
    expectations: &'a [VersionExpectation],
    version: &Version,
) -> Option<&'a VersionExpectation> {
    expectations.iter().find(|expectation| {
        let after_min = expectation
            .min_version
            .as_deref()
            .is_none_or(|min| version >= &Version::parse(min).unwrap());
        let before_max = expectation
            .max_version_exclusive
            .as_deref()
            .is_none_or(|max| version < &Version::parse(max).unwrap());
        after_min && before_max
    })
}

fn convert_keypath(path: &str) -> Keypath {
    Keypath::try_from(path).unwrap()
}

fn convert_script_config(config: &ScriptConfig) -> pb::BtcScriptConfig {
    match config {
        ScriptConfig::Simple { script_type } => {
            bitbox_api::btc::make_script_config_simple(match script_type {
                SimpleType::P2wpkh => pb::btc_script_config::SimpleType::P2wpkh,
                SimpleType::P2wpkhP2sh => pb::btc_script_config::SimpleType::P2wpkhP2sh,
                SimpleType::P2tr => pb::btc_script_config::SimpleType::P2tr,
            })
        }
        ScriptConfig::Multisig {
            threshold,
            xpubs,
            our_xpub_index,
            script_type,
        } => {
            let xpubs = xpubs
                .iter()
                .map(|xpub| xpub.parse::<Xpub>().unwrap())
                .collect::<Vec<_>>();
            bitbox_api::btc::make_script_config_multisig(
                *threshold,
                &xpubs,
                *our_xpub_index,
                match script_type {
                    MultisigScriptType::P2wsh => pb::btc_script_config::multisig::ScriptType::P2wsh,
                    MultisigScriptType::P2wshP2sh => {
                        pb::btc_script_config::multisig::ScriptType::P2wshP2sh
                    }
                },
            )
        }
        ScriptConfig::Policy { policy, keys } => {
            let keys = keys
                .iter()
                .map(|key| bitbox_api::btc::KeyOriginInfo {
                    root_fingerprint: key
                        .root_fingerprint
                        .as_deref()
                        .map(|fingerprint| fingerprint.parse::<Fingerprint>().unwrap()),
                    keypath: key.keypath.as_deref().map(convert_keypath),
                    xpub: key.xpub.parse().unwrap(),
                })
                .collect::<Vec<_>>();
            bitbox_api::btc::make_script_config_policy(policy, &keys)
        }
    }
}

fn convert_script_config_with_keypath(
    config: &ScriptConfigWithKeypath,
) -> pb::BtcScriptConfigWithKeypath {
    pb::BtcScriptConfigWithKeypath {
        script_config: Some(convert_script_config(&config.script_config)),
        keypath: convert_keypath(&config.keypath).to_vec(),
    }
}

fn skip_reason(vector: &TestVector) -> Option<&'static str> {
    if !vector.psbt.options.outputs.is_empty() || !vector.psbt.options.payment_requests.is_empty() {
        return Some("btc_sign_psbt does not expose per-output options or payment requests");
    }
    None
}

fn ecdsa_sighash(sighash: EcdsaSighashType) -> Sighash {
    match sighash {
        EcdsaSighashType::All => Sighash::All,
        other => panic!("unsupported ECDSA sighash {other:?}"),
    }
}

fn taproot_sighash(sighash: TapSighashType) -> Sighash {
    match sighash {
        TapSighashType::All => Sighash::All,
        TapSighashType::Default => Sighash::Default,
        other => panic!("unsupported Taproot sighash {other:?}"),
    }
}

fn signature_slots(psbt: &Psbt) -> BTreeSet<SignatureSlot> {
    let mut slots = BTreeSet::new();
    for (input_index, input) in psbt.inputs.iter().enumerate() {
        for (pubkey, signature) in &input.partial_sigs {
            slots.insert(SignatureSlot {
                input_index,
                kind: SignatureKind::Ecdsa,
                pubkey: Some(pubkey.to_string()),
                leaf_hash: None,
                sighash: ecdsa_sighash(signature.sighash_type),
            });
        }
        if let Some(signature) = &input.tap_key_sig {
            slots.insert(SignatureSlot {
                input_index,
                kind: SignatureKind::TaprootKey,
                pubkey: input.tap_internal_key.map(|pubkey| pubkey.to_string()),
                leaf_hash: None,
                sighash: taproot_sighash(signature.sighash_type),
            });
        }
        for ((pubkey, leaf_hash), signature) in &input.tap_script_sigs {
            slots.insert(SignatureSlot {
                input_index,
                kind: SignatureKind::TaprootScript,
                pubkey: Some(pubkey.to_string()),
                leaf_hash: Some(leaf_hash.to_string()),
                sighash: taproot_sighash(signature.sighash_type),
            });
        }
    }
    slots
}

fn assert_signature_insertions(
    vector: &TestVector,
    before: &BTreeSet<SignatureSlot>,
    after: &BTreeSet<SignatureSlot>,
) {
    assert!(
        before.is_subset(after),
        "{}: signing removed signature slots: before={before:?}, after={after:?}",
        vector.context()
    );
    let inserted = after.difference(before).cloned().collect::<BTreeSet<_>>();
    assert_eq!(
        inserted,
        vector.expected_signatures,
        "{}: inserted signature slots differ",
        vector.context()
    );
}

fn wait_for_stdout(
    stdout: &SimulatorStdout,
    checkpoint: SimulatorStdoutCheckpoint,
) -> SimulatorStdoutSnapshot {
    stdout
        .wait_until_stable(checkpoint, STDOUT_STABLE_FOR, STDOUT_TIMEOUT)
        .unwrap_or_else(|err| panic!("waiting for simulator stdout failed: {err:?}"))
}

fn wait_for_terminal_stdout(
    stdout: &SimulatorStdout,
    checkpoint: SimulatorStdoutCheckpoint,
) -> SimulatorStdoutSnapshot {
    stdout
        .wait_for_terminal_screen(checkpoint, STDOUT_TIMEOUT)
        .unwrap_or_else(|err| panic!("waiting for terminal simulator screen failed: {err:?}"))
}

fn assert_screens(
    vector: &TestVector,
    expected: &[ExpectedScreen],
    snapshot: &SimulatorStdoutSnapshot,
) {
    let actual = snapshot
        .screens()
        .unwrap_or_else(|err| panic!("{}: {err}\n{}", vector.context(), snapshot.raw()));
    let expected: Vec<_> = expected.iter().map(ExpectedScreen::observable).collect();
    assert_eq!(
        actual,
        expected,
        "{}: simulator screens differ\n{}",
        vector.context(),
        snapshot.raw()
    );
}

fn assert_unsupported_error(
    vector: &TestVector,
    device_version: &Version,
    expectation: &VersionExpectation,
    error: &bitbox_api::error::Error,
) {
    let minimum = expectation
        .unsupported_version
        .as_deref()
        .unwrap_or_else(|| {
            panic!(
                "{}: unsupported outcome has no minimum version",
                vector.context()
            )
        });
    let minimum_version = Version::parse(minimum).unwrap();
    assert!(
        device_version < &minimum_version,
        "{}: unsupported outcome selected for firmware {} at or above {}",
        vector.context(),
        device_version,
        minimum
    );

    match error {
        bitbox_api::error::Error::Version(requirement) => assert_eq!(
            *requirement,
            format!(">={minimum}"),
            "{}: wrong client-side firmware requirement",
            vector.context()
        ),
        bitbox_api::error::Error::BitBox(
            bitbox_api::error::BitBoxError::InvalidInput | bitbox_api::error::BitBoxError::Disabled,
        ) => {}
        other => panic!(
            "{}: unexpected error for unsupported firmware: {other:?}",
            vector.context()
        ),
    }
}

fn assert_invalid_input_error(vector: &TestVector, error: &bitbox_api::error::Error) {
    assert!(
        matches!(
            error,
            bitbox_api::error::Error::BitBox(bitbox_api::error::BitBoxError::InvalidInput)
        ),
        "{}: expected invalid input, got {error:?}",
        vector.context()
    );
}

async fn register_script_configs(
    bitbox: &bitbox_api::PairedBitBox<bitbox_api::runtime::TokioRuntime>,
    coin: pb::BtcCoin,
    vector: &TestVector,
) -> Result<(), bitbox_api::error::Error> {
    for registration in &vector.registrations {
        let config = convert_script_config(&registration.script_config);
        let keypath = registration.keypath.as_deref().map(convert_keypath);
        if !bitbox
            .btc_is_script_config_registered(coin, &config, keypath.as_ref())
            .await?
        {
            bitbox
                .btc_register_script_config(
                    coin,
                    &config,
                    keypath.as_ref(),
                    pb::btc_register_script_config_request::XPubType::AutoXpubTpub,
                    Some(&registration.name),
                )
                .await?;
        }
    }
    Ok(())
}

fn convert_coin(coin: Coin) -> pb::BtcCoin {
    match coin {
        Coin::Btc => pb::BtcCoin::Btc,
        Coin::Tbtc => pb::BtcCoin::Tbtc,
        Coin::Ltc => pb::BtcCoin::Ltc,
    }
}

fn convert_format_unit(format_unit: FormatUnit) -> pb::btc_sign_init_request::FormatUnit {
    match format_unit {
        FormatUnit::Default => pb::btc_sign_init_request::FormatUnit::Default,
        FormatUnit::Sat => pb::btc_sign_init_request::FormatUnit::Sat,
    }
}

async fn run_vector(
    bitbox: &bitbox_api::PairedBitBox<bitbox_api::runtime::TokioRuntime>,
    stdout: &SimulatorStdout,
    vector: &TestVector,
) {
    let expectation = match expectation_for(&vector.expectations, bitbox.version()) {
        Some(expectation) => expectation,
        None => {
            let before_first_expectation = vector
                .expectations
                .first()
                .and_then(|expectation| expectation.min_version.as_deref())
                .is_some_and(|min| bitbox.version() < &Version::parse(min).unwrap());
            if before_first_expectation {
                println!(
                    "\t\tSkipping: vector is not applicable to firmware {}",
                    bitbox.version()
                );
                return;
            }
            panic!(
                "no vector expectation matches firmware {}",
                bitbox.version()
            );
        }
    };

    let psbt_bytes = hex::decode(&vector.psbt.transaction)
        .unwrap_or_else(|err| panic!("{}: {err}", vector.context()));
    let mut psbt = Psbt::deserialize(&psbt_bytes)
        .unwrap_or_else(|err| panic!("{}: invalid PSBT: {err}", vector.context()));

    let before = signature_slots(&psbt);
    let coin = convert_coin(vector.coin);

    let setup_checkpoint = stdout.checkpoint();
    let setup_result = register_script_configs(bitbox, coin, vector).await;
    wait_for_stdout(stdout, setup_checkpoint);
    if let Err(error) = setup_result {
        match expectation.outcome {
            Outcome::Unsupported => {
                assert_unsupported_error(vector, bitbox.version(), expectation, &error)
            }
            Outcome::InvalidInput => assert_invalid_input_error(vector, &error),
            Outcome::Success => panic!(
                "{}: registering script config failed: {error:?}",
                vector.context()
            ),
        }

        // Registration output is setup noise, never part of the transaction screen expectation.
        let transaction_checkpoint = stdout.checkpoint();
        let transaction_output = wait_for_stdout(stdout, transaction_checkpoint);
        assert_screens(vector, &expectation.screens, &transaction_output);
        assert_eq!(
            signature_slots(&psbt),
            before,
            "{}: failed setup changed the PSBT",
            vector.context()
        );
        return;
    }

    let force_script_config = vector
        .psbt
        .options
        .force_script_config
        .as_ref()
        .map(convert_script_config_with_keypath);
    let format_unit = convert_format_unit(vector.psbt.options.format_unit);

    let transaction_checkpoint = stdout.checkpoint();
    let sign_result = bitbox
        .btc_sign_psbt(coin, &mut psbt, force_script_config, format_unit)
        .await;
    let transaction_output = match expectation.outcome {
        Outcome::Success => wait_for_terminal_stdout(stdout, transaction_checkpoint),
        Outcome::Unsupported | Outcome::InvalidInput => {
            wait_for_stdout(stdout, transaction_checkpoint)
        }
    };
    assert_screens(vector, &expectation.screens, &transaction_output);

    match expectation.outcome {
        Outcome::Success => {
            sign_result
                .unwrap_or_else(|err| panic!("{}: signing failed: {err:?}", vector.context()));
            let after = signature_slots(&psbt);
            assert_signature_insertions(vector, &before, &after);

            let secp = secp256k1::Secp256k1::new();
            psbt.finalize_mut(&secp)
                .unwrap_or_else(|err| panic!("{}: finalization failed: {err:?}", vector.context()));
            verify_transaction(psbt);
        }
        Outcome::Unsupported => {
            let error = sign_result.unwrap_err();
            assert_unsupported_error(vector, bitbox.version(), expectation, &error);
            assert_eq!(
                signature_slots(&psbt),
                before,
                "{}: unsupported signing changed the PSBT",
                vector.context()
            );
        }
        Outcome::InvalidInput => {
            let error = sign_result.unwrap_err();
            assert_invalid_input_error(vector, &error);
            assert_eq!(
                signature_slots(&psbt),
                before,
                "{}: failed signing changed the PSBT",
                vector.context()
            );
        }
    }
}

#[tokio::test]
async fn test_btc_transaction_vectors() {
    let file: TestVectorFile = serde_json::from_str(VECTOR_JSON).unwrap();

    test_initialized_simulators_with_stdout(async |bitbox, stdout| {
        // Keep restore/pairing stdout out of the first vector checkpoint.
        let startup_checkpoint = stdout.checkpoint();
        wait_for_stdout(stdout, startup_checkpoint);
        for vector in &file.vectors {
            println!("\t\tVector: {}", vector.context());
            if let Some(reason) = skip_reason(vector) {
                println!("\t\tSkipping: {reason}");
            } else {
                run_vector(bitbox, stdout, vector).await;
            }
        }
    })
    .await;
}
